--[[
Project: VitaOnline
File: vehtable-shared.lua
Author(s):      Firzen
                Merlin
                Tjong
                                Sebihunter
]]--
 
gVehicleClasses = {
        [0] = "Unbekannt",
                ["Unbekannt"] = 0,
        [1] = "Motorrad", ["Motorrad"] = 1,
        [2] = "Roller", ["Roller"] = 2,
        [3] = "Crossbike", ["Crossbike"] = 3,
        [4] = "Quadbike", ["Quadbike"] = 4,
        [5] = "Fahrrad", ["Fahrrad"] = 5,
        [6] = "Cabrio", ["Cabrio"] = 6,
        [7] = "Low Rider", ["Low Rider"] = 7,
        [8] = "Gelaendewagen", ["Gelaendewagen"] = 8,
        [9] = "Limousine", ["Limousine"] = 9,
        [10] = "Elektroauto", ["Elektroauto"] = 10,
        [11] = "Sportwagen", ["Sportwagen"] = 11,
        [12] = "Kleinwagen", ["Kleinwagen"] = 12,
        [13] = "Kombiwagen", ["Kombiwagen"] = 13,
        [14] = "Industriefahrzeug", ["Industriefahrzeug"] = 14,
        [15] = "Transportunternehmen", ["Transportunternehmen"] = 15,
        [16] = "Polizei", ["Polizei"] = 16,
        [17] = "Feuerwehr", ["Feuerwehr"] = 17,
        [18] = "Spezialeinheit", ["Spezialeinheit"] = 18,
        [19] = "Sanitaeter", ["Sanitaeter"] = 19,
        [20] = "Militaer", ["Militaer"] = 20,
        [21] = "Spezial", ["Spezial"] = 21,
        [22] = "Zug", ["Zug"] = 22,
        [23] = "Flugzeug", ["Flugzeug"] = 23,
        [24] = "Kampfflugzeug", ["Kampfflugzeug"] = 24,
        [25] = "Hubschrauber", ["Hubschrauber"] = 25,
        [26] = "Kampfhubschrauber", ["Kampfhubschrauber"] = 26,
        [27] = "Boot", ["Boot"] = 27
}
 
 
gVehicleData = {
        [400] = { name = "Landstalker",        class =  8, price =    25000, isPermitted =  true, doors =  5, seats =  4 },
        [401] = { name = "Bravura",            class =  9, price =    9000, isPermitted =  true, doors =  3, seats =  2 },
        [402] = { name = "Buffalo",            class = 11, price =    35000, isPermitted =  true, doors =  3, seats =  2 },
        [403] = { name = "Linerunner",         class = 8, price =    41200, isPermitted =  true, doors =  2, seats =  2 },
	[404] = { name = "Perennial",          class = 13, price =    1000, isPermitted =  true, doors =  5, seats =  4 },
        [405] = { name = "Sentinel",            class =  9, price =    35000, isPermitted =  true, doors =  5, seats =  4 },
        [406] = { name = "Dumper",              class = 21, price =    85200, isPermitted = false, doors =  1, seats =  1, reverse = true },
        [407] = { name = "Firetruck",            class = 17, price =    50200, isPermitted =  true, doors =  3, seats =  2, reverse = true },
        [408] = { name = "Trashmaster",        class = 14, price =    63200, isPermitted =  false, doors =  2, seats =  2, reverse = true },
        [409] = { name = "Stretch",            class = 21, price =    95000, isPermitted =  true, doors =  5, seats =  4 },
        [410] = { name = "Manana",              class =  9, price =    8000, isPermitted =  true, doors =  3, seats =  2 },
        [411] = { name = "Infernus",            class = 11, price =  260000, isPermitted =  true, doors =  3, seats =  2 },
        [412] = { name = "Voodoo",              class =  7, price =    23000, isPermitted =  true, doors =  3, seats =  2 },
        [413] = { name = "Pony",                class = 14, price =    20200, isPermitted =  true, doors =  5, seats =  4 },
        [414] = { name = "Mule",                class = 8, price =    15000, isPermitted =  true, doors =  3, seats =  2 },
	[415] = { name = "Cheetah",            class = 11, price =  240000, isPermitted =  true, doors =  3, seats =  2 },
        [416] = { name = "Ambulance",          class = 19, price =    13200, isPermitted =  false, doors =  5, seats =  4, reverse = true },
        [417] = { name = "Leviathan",          class = 25, price =  60200, isPermitted =  true, doors =  2, seats =  2 },
        [418] = { name = "Moonbeam",            class = 13, price =    17000, isPermitted =  true, doors =  5, seats =  4 },
        [419] = { name = "Esperanto",          class =  9, price =    13200, isPermitted =  true, doors =  3, seats =  2 },
        [420] = { name = "Taxi",                class = 15, price =    20000, isPermitted =  false, doors =  5, seats =  4 },
        [421] = { name = "Washington",          class =  9, price =    34000, isPermitted =  true, doors =  5, seats =  4 },
        [422] = { name = "Bobcat",                class = 8, price =    26000, isPermitted =  true, doors =  3, seats =  2 },
	[423] = { name = "Mr Whoopee",          class = 21, price =    10200, isPermitted =  true, doors =  3, seats =  2, reverse = true },
        [424] = { name = "BF Injection",        class =  8, price =    16500, isPermitted =  true, doors =  0, seats =  2 },
        [425] = { name = "Hunter",              class = 26, price =  1000200, isPermitted = false, doors =  1, seats =  1 },
        [426] = { name = "Premier",            class =  9, price =    25000, isPermitted =  true, doors =  5, seats =  4 },
        [427] = { name = "Enforcer",            class = 16, price =    62200, isPermitted =  false, doors =  5, seats =  4, reverse = true },
        [428] = { name = "Securitycar",        class = 21, price =    45200, isPermitted =  true, doors =  5, seats =  4, reverse = true },
        [429] = { name = "Banshee",            class = 11, price =    90000, isPermitted =  true, doors =  3, seats =  2 },
        [430] = { name = "Predator",            class = 27, price =    120200, isPermitted =  false, doors =  0, seats =  1 },
        [431] = { name = "Bus",                class = 15, price =    40200, isPermitted =  false, doors =  2, seats = -1, reverse = true },
        [432] = { name = "Rhino",              class = 20, price =  2200200, isPermitted = false, doors =  1, seats =  1 },
        [433] = { name = "Barracks",            class = 20, price =    35200, isPermitted =  true, doors =  3, seats =  2, reverse = true },
        [434] = { name = "Hotknife",            class = 21, price =    35000, isPermitted =  true, doors =  3, seats =  2 },
        [436] = { name = "Previon",            class =  9, price =    17500, isPermitted =  true, doors =  3, seats =  2 },
        [437] = { name = "Coach",              class = 15, price =    50200, isPermitted =  false, doors =  2, seats = -1, reverse = true },
        [438] = { name = "Cabbie",              class = 15, price =    10200, isPermitted =  false, doors =  5, seats =  4 },
        [439] = { name = "Stallion",            class =  6, price =    19500, isPermitted =  true, doors =  3, seats =  2 },
        [440] = { name = "Rumpo",                class = 8, price =    9500, isPermitted =  true, doors =  3, seats =  2 },
	[442] = { name = "Romero",              class = 21, price =    24000, isPermitted =  true, doors =  3, seats =  2 },
        [443] = { name = "Packer",                class = 12, price =    40200, isPermitted =  true, doors =  3, seats =  2 },
	[444] = { name = "Monster",            class =  8, price =    120200, isPermitted = false, doors =  3, seats =  2 },
        [445] = { name = "Admiral",            class =  9, price =    35000, isPermitted =  true, doors =  5, seats =  4 },
        [446] = { name = "Squallo",            class = 27, price =    80200, isPermitted =  true, doors =  0, seats =  1 },
        [447] = { name = "Seasparrow",          class = 26, price =    80200, isPermitted = false, doors =  2, seats =  2 },
        [448] = { name = "Pizzaboy",            class =  2, price =    1200, isPermitted =  false, doors =  0, seats =  1 },
        [451] = { name = "Turismo",            class = 11, price =  245000, isPermitted =  true, doors =  3, seats =  2 },
        [452] = { name = "Speeder",            class = 27, price =    70200, isPermitted =  true, doors =  0, seats =  1 },
        [453] = { name = "Reefer",              class = 27, price =    30200, isPermitted =  true, doors =  0, seats =  1 },
        [454] = { name = "Tropic",              class = 27, price =    100200, isPermitted =  true, doors =  0, seats =  1 },
        [455] = { name = "Flatbed",                class = 8, price =    20200, isPermitted =  true, doors =  3, seats =  2 },
	[456] = { name = "Yankee",                class = 8, price =    11000, isPermitted =  true, doors =  3, seats =  2 },
	[457] = { name = "Caddy",              class = 21, price =    2200, isPermitted =  false, doors =  0, seats =  2 },
        [458] = { name = "Solair",              class = 13, price =    18000, isPermitted =  true, doors =  5, seats =  4 },
        [460] = { name = "Skimmer",            class = 23, price =    35200, isPermitted =  true, doors =  1, seats =  1 },
        [461] = { name = "PCJ-600",            class =  1, price =    8600, isPermitted =  true, doors =  0, seats =  2 },
        [462] = { name = "Faggio",              class =  2, price =    2400, isPermitted =  true, doors =  0, seats =  2 },
        [463] = { name = "Freeway",            class =  1, price =    13750, isPermitted =  true, doors =  0, seats =  2 },
        [466] = { name = "Glendale",            class =  9, price =    20000, isPermitted =  true, doors =  5, seats =  4 },
        [467] = { name = "Oceanic",            class =  9, price =    21000, isPermitted =  true, doors =  5, seats =  4 },
        [468] = { name = "Sanchez",            class =  3, price =    14200, isPermitted = false, doors =  0, seats =  2 },
        [469] = { name = "Sparrow",            class = 25, price =    50200, isPermitted =  true, doors =  2, seats =  2 },
        [470] = { name = "Patriot",            class =  8, price =    53000, isPermitted =  true, doors =  5, seats =  4 },
        [471] = { name = "Quad",                class =  4, price =    9200, isPermitted = false, doors =  0, seats =  2 },
        [472] = { name = "Kuestenwache",        class = 27, price =    21200, isPermitted =  true, doors =  0, seats =  1 },
        [473] = { name = "Dinghy",              class = 27, price =    10200, isPermitted =  true, doors =  0, seats =  1 },
        [472] = { name = "Coastguard",            class =  27, price =    14200, isPermitted = true, doors =  0, seats =  2 },
        [474] = { name = "Hermes",              class =  9, price =    19000, isPermitted =  true, doors =  3, seats =  2 },
        [475] = { name = "Sabre",              class = 11, price =    26000, isPermitted =  true, doors =  3, seats =  2 },
        [476] = { name = "Rustler",            class = 24, price =    70200, isPermitted = false, doors =  1, seats =  1 },
        [477] = { name = "ZR-350",              class = 11, price =    45000, isPermitted =  true, doors =  3, seats =  2 },
        [478] = { name = "Walton",              class = 14, price =    8500, isPermitted =  true, doors =  2, seats =  2 },
        [479] = { name = "Regina",              class = 13, price =    1800, isPermitted =  true, doors =  5, seats =  4 },
        [480] = { name = "Comet",              class =  6, price =  109000, isPermitted =  true, doors =  3, seats =  2 },
        [481] = { name = "BMX",                class =  5, price =    350, isPermitted =  true, doors =  0, seats =  1 },
        [482] = { name = "Burrito",            class = 14, price =    22200, isPermitted =  true, doors =  4, seats =  4 },
        [483] = { name = "Camper",              class = 21, price =    16400, isPermitted =  true, doors =  4, seats =  2 },
        [484] = { name = "Marquis",            class = 27, price =    50200, isPermitted =  true, doors =  0, seats =  1 },
        [485] = { name = "Baggage",            class = 21, price =    2200, isPermitted = false, doors =  0, seats =  1, reverse = true },
        [486] = { name = "Dozer",              class = 21, price =    25200, isPermitted = false, doors =  1, seats =  1, reverse = true },
        [487] = { name = "Maverick",            class = 25, price =    80200, isPermitted =  true, doors =  4, seats =  4 },
        [488] = { name = "NewsMaverick",        class = 25, price =    80200, isPermitted =  true, doors =  3, seats =  2 },
	[489] = { name = "Rancher",            class =  8, price =    40000, isPermitted =  true, doors =  3, seats =  2 },
        [490] = { name = "FBI-Rancher",        class = 18, price =    45000, isPermitted =  false, doors =  5, seats =  4 },
        [491] = { name = "Virgo",              class =  9, price =    9000, isPermitted =  true, doors =  3, seats =  2 },
        [492] = { name = "Greenwood",          class =  9, price =    7000, isPermitted =  true, doors =  5, seats =  4 },
        [493] = { name = "Jetmax",              class = 27, price =    85200, isPermitted =  true, doors =  0, seats =  1 },
        [495] = { name = "Sandking",            class =  8, price =    50200, isPermitted =  true, doors =  3, seats =  2 },
        [496] = { name = "Blista-Compact",      class = 12, price =    35000, isPermitted =  true, doors =  3, seats =  2 },
        [497] = { name = "Maverick",            class = 25, price =    45200, isPermitted =  true, doors =  4, seats =  4 },
        [498] = { name = "Boxvill",                class = 8, price =    12200, isPermitted =  true, doors =  3, seats =  2 },
	[499] = { name = "Benson",                class = 8, price =    12200, isPermitted =  true, doors =  2, seats =  2 },
	[500] = { name = "Mesa",                class =  8, price =    25000, isPermitted =  true, doors =  3, seats =  2 },
        [504] = { name = "Bloodring Banger",    class =  9, price =    8200, isPermitted =  true, doors =  0, seats =  2 },
        [505] = { name = "Rancher",            class =  8, price =    40200, isPermitted =  true, doors =  3, seats =  2 },
        [506] = { name = "Super-GT",            class = 11, price =  19000, isPermitted =  true, doors =  3, seats =  2 },
        [507] = { name = "Elegant",            class =  9, price =    35000, isPermitted =  true, doors =  5, seats =  4 },
        [508] = { name = "Journey",            class = 21, price =    22200, isPermitted =  true, doors =  3, seats =  2 },
        [509] = { name = "Bike",                class =  5, price =      350, isPermitted =  true, doors =  0, seats =  1 },
        [510] = { name = "Mountain Bike",      class =  5, price =    350, isPermitted =  true, doors =  0, seats =  1 },
        [511] = { name = "Beagle",              class = 23, price =    35200, isPermitted =  true, doors =  2, seats =  2 },
        [512] = { name = "Cropduster",          class = 24, price =    20200, isPermitted = false, doors =  1, seats =  1 },
        [513] = { name = "Stuntplane",          class = 23, price =    45200, isPermitted =  true, doors =  1, seats =  1 },
        [514] = { name = "Tanklaster",                class = 8, price =    40200, isPermitted =  true, doors =  3, seats =  2 },
	[515] = { name = "Roadtrain",          class = 14, price =    40200, isPermitted =  true, doors =  2, seats =  2, reverse = true },
        [516] = { name = "Nebula",              class =  9, price =    16200, isPermitted =  true, doors =  5, seats =  4 },
        [517] = { name = "Majestic",            class =  9, price =    25000, isPermitted =  true, doors =  3, seats =  2 },
        [518] = { name = "Buccaneer",          class =  9, price =    18200, isPermitted =  true, doors =  3, seats =  2 },
        [519] = { name = "Shamal",              class = 23, price =    80200, isPermitted =  true, doors =  1, seats =  1 },
        [520] = { name = "Hydra",              class = 24, price =  800200, isPermitted = false, doors =  1, seats =  1 },
        [521] = { name = "FCR-900",            class =  1, price =    13000, isPermitted =  true, doors =  0, seats =  2 },
        [522] = { name = "NRG-500",            class =  1, price =    41200, isPermitted = false, doors =  0, seats =  2 },
        [523] = { name = "HPV1000",            class = 16, price =    11200, isPermitted =  true, doors =  0, seats =  2 },
        [524] = { name = "Cement Truck",       class = 8, price =    40200, isPermitted =  true, doors =  3, seats =  2 },
	[525] = { name = "Abschlepper",        class = 21, price =    14200, isPermitted =  true, doors =  2, seats =  2, reverse = true },
        [526] = { name = "Fortune",            class =  9, price =    15600, isPermitted =  true, doors =  3, seats =  2 },
        [527] = { name = "Cadrona",            class = 10, price =        12200, isPermitted =  true, doors =  3, seats =  2 },
        [528] = { name = "FBI-Truck",          class = 18, price =    36200, isPermitted =  false, doors =  3, seats =  2 },
        [529] = { name = "Willard",            class =  9, price =    8200, isPermitted =  true, doors =  5, seats =  4 },
        [530] = { name = "Forklift",            class = 21, price =    2200, isPermitted = false, doors =  0, seats =  1, reverse = true },
        [531] = { name = "Traktor",            class =  27, price =    8200, isPermitted = true, doors =  0, seats =  2 },
	[532] = { name = "Maehdrescher",        class = 21, price =    60200, isPermitted =  false, doors =  1, seats =  1 },
        [533] = { name = "Feltzer",            class =  6, price =    24300, isPermitted =  true, doors =  3, seats =  2 },
        [534] = { name = "Remington",          class =  7, price =    30000, isPermitted =  true, doors =  3, seats =  2 },
        [535] = { name = "Slamvan",            class =  7, price =    34000, isPermitted =  true, doors =  3, seats =  2 },
        [536] = { name = "Blade",              class =  7, price =    35000, isPermitted =  true, doors =  3, seats =  2 },
        [538] = { name = "Brownstreak",        class = 22, price =  599200, isPermitted =  true, doors =  1, seats =  1 },
        [539] = { name = "Vortex",              class = 21, price =    26000, isPermitted = false, doors =  0, seats =  1 },
        [540] = { name = "Vincent",            class =  9, price =    33000, isPermitted =  true, doors =  5, seats =  4 },
        [541] = { name = "Bullet",              class = 11, price =  160000, isPermitted =  true, doors =  3, seats =  2 },
        [542] = { name = "Clover",              class =  9, price =    13000, isPermitted =  true, doors =  3, seats =  2 },
        [543] = { name = "Sadler",                class = 8, price =    21000, isPermitted =  true, doors =  3, seats =  2 },
	[544] = { name = "Firetruck+Leiter",     class = 17, price =    54200, isPermitted =  false, doors =  3, seats =  2, reverse = true },
        [545] = { name = "Hustler",            class = 21, price =    15200, isPermitted =  true, doors =  3, seats =  2 },
        [546] = { name = "Intruder",            class =  9, price =    17500, isPermitted =  true, doors =  5, seats =  4 },
        [547] = { name = "Primo",              class = 10, price =    36000, isPermitted =  true, doors =  5, seats =  4 },
        [548] = { name = "Cargobob",            class = 25, price =   80200, isPermitted =  true, doors =  2, seats =  2 },
        [549] = { name = "Tampa",              class =  9, price =    12000, isPermitted =  true, doors =  3, seats =  2 },
        [550] = { name = "Sunrise",            class =  9, price =    19000, isPermitted =  true, doors =  5, seats =  4 },
        [551] = { name = "Merit",              class =  9, price =        15600, isPermitted =  true, doors =  5, seats =  4 },
        [552] = { name = "Utility-Van",        class = 14, price =    16200, isPermitted =  false, doors =  2, seats =  2 },
        [553] = { name = "Nevada",              class = 23, price =    65200, isPermitted =  true, doors =  1, seats =  1 },
        [554] = { name = "Yosemite",            class = 14, price =    27000, isPermitted =  true, doors =  3, seats =  2 },
        [555] = { name = "Windsor",            class =  6, price =    35000, isPermitted =  true, doors =  3, seats =  2 },
        [558] = { name = "Uranus",              class = 11, price =    35000, isPermitted =  true, doors =  3, seats =  2 },
        [559] = { name = "Jester",              class = 11, price =    35000, isPermitted =  true, doors =  3, seats =  2 },
        [560] = { name = "Sultan",              class =  9, price =    37000, isPermitted =  true, doors =  5, seats =  4 },
        [561] = { name = "Stratum",            class = 13, price =    34000, isPermitted =  true, doors =  5, seats =  4 },
        [562] = { name = "Elegy",              class =  9, price =    38000, isPermitted =  true, doors =  3, seats =  2 },
        [563] = { name = "Raindance",          class = 25, price =    60200, isPermitted =  true, doors =  2, seats =  2 },
        [565] = { name = "Flash",              class = 12, price =    36000, isPermitted =  true, doors =  3, seats =  2 },
        [566] = { name = "Tahoma",              class =  7, price =    32000, isPermitted =  true, doors =  5, seats =  4 },
        [567] = { name = "Savanna",            class =  7, price =    19000, isPermitted =  true, doors =  5, seats =  4 },
        [568] = { name = "Bandito",            class =  8, price =    14200, isPermitted = false, doors =  0, seats =  1 },
        [570] = { name = "Streak-Trailer",      class = 22, price =  399200, isPermitted =  true, doors = -1, seats = -1 },
        [571] = { name = "Kart",                class = 21, price =    2000, isPermitted = false, doors =  0, seats =  1 },
        [572] = { name = "Mower",              class = 21, price =    5000, isPermitted = true, doors =  0, seats =  1 },
        [573] = { name = "Dune",                class =  8, price =    70200, isPermitted =  true, doors =  3, seats =  2 },
        [574] = { name = "Sweeper",            class = 21, price =    6200, isPermitted =  false, doors =  1, seats =  1 },
        [575] = { name = "Broadway",            class =  7, price =    19000, isPermitted =  true, doors =  3, seats =  2 },
        [576] = { name = "Tornado",            class =  7, price =    18500, isPermitted =  true, doors =  3, seats =  2 },
        [577] = { name = "AT-400",              class = 23, price =  5000200, isPermitted =  true, doors =  1, seats =  2 },
        [578] = { name = "DFT-30",              class = 14, price =    18200, isPermitted =  false, doors =  3, seats =  2, reverse = true },
        [579] = { name = "Huntley",            class =  8, price =    40200, isPermitted =  true, doors =  5, seats =  4 },
        [580] = { name = "Stafford",            class =  9, price =    33200, isPermitted =  true, doors =  5, seats =  4 },
        [581] = { name = "BF-400",              class =  1, price =    13200, isPermitted =  true, doors =  0, seats =  2 },
        [582] = { name = "Newsvan",            class = 14, price =    16200, isPermitted =  false, doors =  4, seats =  4 },
        [583] = { name = "Tug",                class = 21, price =    2200, isPermitted =  false, doors =  1, seats =  1 },
        [585] = { name = "Emperor",            class =  9, price =    34000, isPermitted =  true, doors =  5, seats =  4 },
        [586] = { name = "Wayfarer",            class =  1, price =    9200, isPermitted =  true, doors =  0, seats =  2 },
        [587] = { name = "Euros",              class = 11, price =    35000, isPermitted =  true, doors =  3, seats =  2 },
        [588] = { name = "Hot-Dog",            class = 21, price =    10200, isPermitted =  true, doors =  3, seats =  2, reverse = true },
        [589] = { name = "Club",                class = 12, price =    35000, isPermitted =  true, doors =  3, seats =  2 },
        [592] = { name = "Andromada",           class = 23, price =    6000200, isPermitted =  true, doors =  1, seats =  2 },
		[593] = { name = "Dodo",                class = 23, price =    20200, isPermitted =  true, doors =  1, seats =  1 },
        [595] = { name = "Launch",              class = 27, price =    40200, isPermitted =  true, doors =  0, seats =  1 },
        [596] = { name = "LSPD",                class = 16, price =     30000, isPermitted =  false, doors =  5, seats =  4 },
        [597] = { name = "SFPD",                class = 16, price =    260000, isPermitted =  false, doors =  5, seats =  4 },
        [598] = { name = "LVPD",                class = 16, price =    35000, isPermitted =  false, doors =  5, seats =  4 }, --Normal price 10500 - here we got a cheetah mod
        [599] = { name = "Ranger",              class = 16, price =    35000, isPermitted =  true, doors =  3, seats =  2 },
        [600] = { name = "Picador",            class = 14, price =    21000, isPermitted =  true, doors =  2, seats =  2 },
        [601] = { name = "SWAT",                class = 18, price =    40200, isPermitted =  false, doors =  2, seats =  2 },
        [602] = { name = "Alpha",              class = 11, price =    35200, isPermitted =  true, doors =  3, seats =  2 },
        [603] = { name = "Phoenix",            class = 11, price =    38000, isPermitted =  true, doors =  5, seats =  4 }
}