--[[
Project: VitaOnline
File: perso-client.lua
Author(s):	Sebihunter
]]--

AusweisGUI_Label = {}
AusweisGUI_Image = {}

function createPerso()
	AusweisGUI_Image[1] = guiCreateStaticImage(0.3512,0.701,0.2935,0.2981,"images/ausweis.png",true)
	guiSetVisible ( AusweisGUI_Image[1], false )

	AusweisGUI_Label[1] = guiCreateLabel(0.356,0.7076,0.1929,0.0143,"Ausweis der Republik San Andreas",true)
	guiLabelSetColor(AusweisGUI_Label[1],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[1],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[1],"left",false)
	guiSetFont(AusweisGUI_Label[1],"default-bold-small")
	guiSetVisible ( AusweisGUI_Label[1], false )

	AusweisGUI_Label[2] = guiCreateLabel(0.356,0.8933,0.0958,0.0171,"Lichtbild",true)
	guiLabelSetColor(AusweisGUI_Label[2],125,125,125)
	guiLabelSetVerticalAlign(AusweisGUI_Label[2],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[2],"center",false)
	guiSetFont(AusweisGUI_Label[2],"default-small")
	guiSetVisible ( AusweisGUI_Label[2], false )

	AusweisGUI_Label[3] = guiCreateLabel(0.4554,0.7267,0.0536,0.0152,"Name:",true)
	guiLabelSetColor(AusweisGUI_Label[3],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[3],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[3],"left",false)
	guiSetFont(AusweisGUI_Label[3],"default-bold-small")
	guiSetVisible ( AusweisGUI_Label[3], false )

	AusweisGUI_Label[4] = guiCreateLabel(0.4554,0.7419,0.081,0.0224,"Sebastian Hunter",true)
	guiLabelSetColor(AusweisGUI_Label[4],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[4],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[4],"left",false)
	guiSetVisible ( AusweisGUI_Label[4], false )

	AusweisGUI_Label[5] = guiCreateLabel(0.4554,0.759,0.0536,0.0152,"Geburtsdatum:",true)
	guiLabelSetColor(AusweisGUI_Label[5],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[5],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[5],"left",false)
	guiSetFont(AusweisGUI_Label[5],"default-bold-small")
	guiSetVisible ( AusweisGUI_Label[5], false )

	AusweisGUI_Label[6] = guiCreateLabel(0.4554,0.7743,0.081,0.0224,"30.03.1984",true)
	guiLabelSetColor(AusweisGUI_Label[6],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[6],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[6],"left",false)
	guiSetVisible ( AusweisGUI_Label[6], false )

	AusweisGUI_Label[7] = guiCreateLabel(0.4554,0.7905,0.0536,0.0152,"Geschlecht:",true)
	guiLabelSetColor(AusweisGUI_Label[7],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[7],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[7],"left",false)
	guiSetFont(AusweisGUI_Label[7],"default-bold-small")
	guiSetVisible ( AusweisGUI_Label[7], false )

	AusweisGUI_Label[8] = guiCreateLabel(0.4554,0.8057,0.081,0.0224,"M#nnlich",true)
	guiLabelSetColor(AusweisGUI_Label[8],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[8],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[8],"left",false)
	guiSetVisible ( AusweisGUI_Label[8], false )

	AusweisGUI_Label[9] = guiCreateLabel(0.4554,0.8229,0.0536,0.0152,"Beruf:",true)
	guiLabelSetColor(AusweisGUI_Label[9],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[9],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[9],"left",false)
	guiSetFont(AusweisGUI_Label[9],"default-bold-small")
	guiSetVisible ( AusweisGUI_Label[9], false )

	AusweisGUI_Label[10] = guiCreateLabel(0.4554,0.8381,0.2,0.0224,"Autoverkäufer",true)
	guiLabelSetColor(AusweisGUI_Label[10],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[10],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[10],"left",false)
	guiSetVisible ( AusweisGUI_Label[10], false )

	AusweisGUI_Label[11] = guiCreateLabel(0.356,0.9105,0.0536,0.0152,"Führerschein:",true)
	guiLabelSetColor(AusweisGUI_Label[11],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[11],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[11],"left",false)
	guiSetFont(AusweisGUI_Label[11],"default-bold-small")
	guiSetVisible ( AusweisGUI_Label[11], false )

	AusweisGUI_Label[12] = guiCreateLabel(0.356,0.9257,0.0536,0.0152,"Motorradschein:",true)
	guiLabelSetColor(AusweisGUI_Label[12],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[12],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[12],"left",false)
	guiSetFont(AusweisGUI_Label[12],"default-bold-small")
	guiSetVisible ( AusweisGUI_Label[12], false )

	AusweisGUI_Label[13] = guiCreateLabel(0.4125,0.9105,0.0393,0.0224,"Ja",true)
	guiLabelSetColor(AusweisGUI_Label[13],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[13],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[13],"left",false)
	guiSetVisible ( AusweisGUI_Label[13], false )

	AusweisGUI_Label[14] = guiCreateLabel(0.4125,0.9257,0.0393,0.0224,"Nein",true)
	guiLabelSetColor(AusweisGUI_Label[14],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[14],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[14],"left",false)
	guiSetVisible ( AusweisGUI_Label[14], false )

	AusweisGUI_Label[15] = guiCreateLabel(0.4351,0.9105,0.0738,0.0124,"LKW-Schein:",true)
	guiLabelSetColor(AusweisGUI_Label[15],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[15],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[15],"left",false)
	guiSetFont(AusweisGUI_Label[15],"default-bold-small")
	guiSetVisible ( AusweisGUI_Label[15], false )

	AusweisGUI_Label[16] = guiCreateLabel(0.4351,0.9257,0.0595,0.0124,"Flugschein:",true)
	guiLabelSetColor(AusweisGUI_Label[16],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[16],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[16],"left",false)
	guiSetFont(AusweisGUI_Label[16],"default-bold-small")
	guiSetVisible ( AusweisGUI_Label[16], false )

	AusweisGUI_Label[17] = guiCreateLabel(0.5042,0.9105,0.0393,0.0224,"Ja",true)
	guiLabelSetColor(AusweisGUI_Label[17],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[17],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[17],"left",false)
	guiSetVisible ( AusweisGUI_Label[17], false )

	AusweisGUI_Label[18] = guiCreateLabel(0.5042,0.9257,0.0393,0.0224,"Ja",true)
	guiLabelSetColor(AusweisGUI_Label[18],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[18],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[18],"left",false)
	guiSetVisible ( AusweisGUI_Label[18], false )

	AusweisGUI_Label[19] = guiCreateLabel(0.5342,0.9105,0.0738,0.0124,"Waffenschein:",true)
	guiLabelSetColor(AusweisGUI_Label[19],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[19],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[19],"left",false)
	guiSetFont(AusweisGUI_Label[19],"default-bold-small")
	guiSetVisible ( AusweisGUI_Label[19], false )

	AusweisGUI_Label[20] = guiCreateLabel(0.5342,0.9257,0.0595,0.0124,"Pkte. in Fleischberg:",true)
	guiLabelSetColor(AusweisGUI_Label[20],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[20],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[20],"left",false)
	guiSetFont(AusweisGUI_Label[20],"default-bold-small")
	guiSetVisible ( AusweisGUI_Label[20], false )

	AusweisGUI_Label[21] = guiCreateLabel(0.6042,0.9105,0.0393,0.0224,"Ja",true)
	guiLabelSetColor(AusweisGUI_Label[21],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[21],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[21],"left",false)
	guiSetVisible ( AusweisGUI_Label[21], false )

	AusweisGUI_Label[22] = guiCreateLabel(0.6042,0.9257,0.0393,0.0224,"2",true)
	guiLabelSetColor(AusweisGUI_Label[22],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[22],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[22],"left",false)
	guiSetVisible ( AusweisGUI_Label[22], false )

	AusweisGUI_Label[23] = guiCreateLabel(0.5342,0.8953,0.0738,0.0124,"Temp. Fschein:",true)
	guiLabelSetColor(AusweisGUI_Label[23],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[23],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[23],"left",false)
	guiSetFont(AusweisGUI_Label[23],"default-bold-small")
	guiSetVisible ( AusweisGUI_Label[23], false )

	AusweisGUI_Label[24] = guiCreateLabel(0.6042,0.8953,1,0.0224,"Nein",true)
	guiLabelSetColor(AusweisGUI_Label[24],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[24],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[24],"left",false)
	guiSetVisible ( AusweisGUI_Label[24], false )

	AusweisGUI_Label[25] = guiCreateLabel(0.5342,0.8801,0.0738,0.0124,"PA Note:",true)
	guiLabelSetColor(AusweisGUI_Label[25],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[25],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[25],"left",false)
	guiSetFont(AusweisGUI_Label[25],"default-bold-small")
	guiSetVisible ( AusweisGUI_Label[25], false )

	AusweisGUI_Label[26] = guiCreateLabel(0.6042,0.8801,1,0.0224,"0%",true)
	guiLabelSetColor(AusweisGUI_Label[26],0,0,0)
	guiLabelSetVerticalAlign(AusweisGUI_Label[26],"top")
	guiLabelSetHorizontalAlign(AusweisGUI_Label[26],"left",false)
	guiSetVisible ( AusweisGUI_Label[26], false )
end


function zeigePerso (name, geburtsdatum, geschlecht, beruf, fschein, mschein, gschein, flschein, wschein, tschein, pif, skinid, panote)
	hideallll ( )
	guiSetText ( AusweisGUI_Label[4], name )
	guiSetText ( AusweisGUI_Label[6], geburtsdatum )
	guiSetText ( AusweisGUI_Label[8], geschlecht )
	guiSetText ( AusweisGUI_Label[10], beruf )
	guiSetText ( AusweisGUI_Label[13], fschein )
	guiSetText ( AusweisGUI_Label[14], mschein )
	guiSetText ( AusweisGUI_Label[17], gschein )
	guiSetText ( AusweisGUI_Label[18], flschein )	
	guiSetText ( AusweisGUI_Label[21], wschein )
	guiSetText ( AusweisGUI_Label[22], pif )
	guiSetText ( AusweisGUI_Label[24], tschein )
	guiSetText ( AusweisGUI_Label[26], panote.."%" )
	guiSetVisible ( AusweisGUI_Image[1], true )
	guiSetVisible ( AusweisGUI_Label[1], true )
	guiSetVisible ( AusweisGUI_Label[2], true )
	guiSetVisible ( AusweisGUI_Label[3], true )
	guiSetVisible ( AusweisGUI_Label[4], true )
	guiSetVisible ( AusweisGUI_Label[5], true )
	guiSetVisible ( AusweisGUI_Label[6], true )
	guiSetVisible ( AusweisGUI_Label[7], true )
	guiSetVisible ( AusweisGUI_Label[8], true )
	guiSetVisible ( AusweisGUI_Label[9], true )
	guiSetVisible ( AusweisGUI_Label[10], true )
	guiSetVisible ( AusweisGUI_Label[11], true )
	guiSetVisible ( AusweisGUI_Label[12], true )
	guiSetVisible ( AusweisGUI_Label[13], true )
	guiSetVisible ( AusweisGUI_Label[14], true )
	guiSetVisible ( AusweisGUI_Label[15], true )
	guiSetVisible ( AusweisGUI_Label[16], true )
	guiSetVisible ( AusweisGUI_Label[17], true )
	guiSetVisible ( AusweisGUI_Label[18], true )
	guiSetVisible ( AusweisGUI_Label[19], true )
	guiSetVisible ( AusweisGUI_Label[20], true )
	guiSetVisible ( AusweisGUI_Label[21], true )
	guiSetVisible ( AusweisGUI_Label[22], true )
	guiSetVisible ( AusweisGUI_Label[23], true )
	guiSetVisible ( AusweisGUI_Label[24], true )
	guiSetVisible ( AusweisGUI_Label[25], true )
	guiSetVisible ( AusweisGUI_Label[26], true )	
	guiMoveToBack( AusweisGUI_Image[1] )
	AusweisGUI_Skinpic = guiCreateStaticImage(0.3577,0.739,0.0911,0.1438,"images/skins/"..tonumber(skinid)..".png",true)
	--guiSetVisible ( AusweisGUI_Skinpic, false )
	--destroyElement( AusweisGUI_Skinpic )
	showTutorialMessage("perso_1", "Du kannst den Personalausweis mit einem Klick auf ihn wieder schließen.")
end

addEvent("zeigePerso", true)
addEventHandler( "zeigePerso", getRootElement(), zeigePerso)

function persoClick ( button, state, absoluteX, absoluteY )
	if source == AusweisGUI_Image[1] or source == AusweisGUI_Skinpic then
		guiSetVisible ( AusweisGUI_Image[1], false )
		guiSetVisible ( AusweisGUI_Label[1], false )
		guiSetVisible ( AusweisGUI_Label[2], false )
		guiSetVisible ( AusweisGUI_Label[3], false )
		guiSetVisible ( AusweisGUI_Label[4], false )
		guiSetVisible ( AusweisGUI_Label[5], false )
		guiSetVisible ( AusweisGUI_Label[6], false )
		guiSetVisible ( AusweisGUI_Label[7], false )
		guiSetVisible ( AusweisGUI_Label[8], false )
		guiSetVisible ( AusweisGUI_Label[9], false )
		guiSetVisible ( AusweisGUI_Label[10], false )

		guiSetVisible ( AusweisGUI_Label[11], false )
		guiSetVisible ( AusweisGUI_Label[12], false )
		guiSetVisible ( AusweisGUI_Label[13], false )
		guiSetVisible ( AusweisGUI_Label[14], false )
		guiSetVisible ( AusweisGUI_Label[15], false )
		guiSetVisible ( AusweisGUI_Label[16], false )
		guiSetVisible ( AusweisGUI_Label[17], false )
		guiSetVisible ( AusweisGUI_Label[18], false )
		guiSetVisible ( AusweisGUI_Label[19], false )
		guiSetVisible ( AusweisGUI_Label[20], false )
		guiSetVisible ( AusweisGUI_Label[21], false )
		guiSetVisible ( AusweisGUI_Label[22], false )
		guiSetVisible ( AusweisGUI_Label[23], false )
		guiSetVisible ( AusweisGUI_Label[24], false )
		guiSetVisible ( AusweisGUI_Label[25], false )
		guiSetVisible ( AusweisGUI_Label[26], false )		
		guiSetVisible ( AusweisGUI_Skinpic, false )
		destroyElement( AusweisGUI_Skinpic )
	end
end


function hideallll ( )
		guiSetVisible ( AusweisGUI_Image[1], false )
		guiSetVisible ( AusweisGUI_Label[1], false )
		guiSetVisible ( AusweisGUI_Label[2], false )
		guiSetVisible ( AusweisGUI_Label[3], false )
		guiSetVisible ( AusweisGUI_Label[4], false )
		guiSetVisible ( AusweisGUI_Label[5], false )
		guiSetVisible ( AusweisGUI_Label[6], false )
		guiSetVisible ( AusweisGUI_Label[7], false )
		guiSetVisible ( AusweisGUI_Label[8], false )
		guiSetVisible ( AusweisGUI_Label[9], false )
		guiSetVisible ( AusweisGUI_Label[10], false )

		guiSetVisible ( AusweisGUI_Label[11], false )
		guiSetVisible ( AusweisGUI_Label[12], false )
		guiSetVisible ( AusweisGUI_Label[13], false )
		guiSetVisible ( AusweisGUI_Label[14], false )
		guiSetVisible ( AusweisGUI_Label[15], false )
		guiSetVisible ( AusweisGUI_Label[16], false )
		guiSetVisible ( AusweisGUI_Label[17], false )
		guiSetVisible ( AusweisGUI_Label[18], false )
		guiSetVisible ( AusweisGUI_Label[19], false )
		guiSetVisible ( AusweisGUI_Label[20], false )
		guiSetVisible ( AusweisGUI_Label[21], false )
		guiSetVisible ( AusweisGUI_Label[22], false )
		guiSetVisible ( AusweisGUI_Label[23], false )
		guiSetVisible ( AusweisGUI_Label[24], false )
		guiSetVisible ( AusweisGUI_Label[25], false )
		guiSetVisible ( AusweisGUI_Label[26], false )
		if AusweisGUI_Skinpic and guiGetVisible(AusweisGUI_Skinpic) == true then
			guiSetVisible ( AusweisGUI_Skinpic, false )
			destroyElement( AusweisGUI_Skinpic )
		end
end
addEventHandler ( "onClientGUIClick", getRootElement(), persoClick)